### ISSUE TITLE
move unicode and font size under font options (replacing unicode button)

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/SikhiToTheMax-Web#113]
its overlapped by sharing on mobile

**Comment by navdeepsinghkhalsa** [comment]
We can move Unicode when and add other font options under Display Options, but I don't think we should move Larivaar. Toggling Larivaar on displays the Larivaar Assist button, which not work effectively inside a menu. Sharing CSS has to be updated to fall on the next line and not overlap. This is because the Display Options line sticks to the top of the page when scrolling and takes precedence.

**Comment by ManjotS** [comment]
can we make larivaar an icon like in learn larivaar instead of a text button

**Comment by ManjotS** [comment]
I'd like to change the unicode button into a font drop down and we can move font size and unicode in there in prep for adding other font options like font face, translation size etc

**Comment by ManjotS** [comment]
dependent on #233
